name: Build and Deploy

on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  pages: write
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: typst-community/setup-typst@v3
    - name: Uncomment includes
      run: find src -name '*.typ' -exec perl -i -pe 's/^\/\/ \#include/\#include/' {} \;
    - name: Build PDFs
      run: make

    # - run: sudo apt-get update && sudo apt-get install -y ghostscript
    # - name: Invert PDFs
    #   run: |
    #     for f in `find build -name '*.pdf'`; do
    #       gs -o "`dirname $f`/_`basename $f`" -sDEVICE=pdfwrite -c "{1 exch sub}{1 exch sub}{1 exch sub}{1 exch sub} setcolortransfer" -f $f
    #     done
    
    - name: Prepare Jekyll
      run: |
        mv build/* .
        rm src fonts -rf

    - name: Build website with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: .
        destination: ./_site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

    - name: Delete past workflow runs
      # | jq -r '.workflow_runs[] | [ .id, .display_title, .conclusion ] | @tsv' \
      run: gh api /repos/${{ github.repository }}/actions/runs \
        | jq -r '.workflow_runs[] | .id' \
        | tail -n +2 \
        | xargs -tI{} gh api -X DELETE /repos/${{ github.repository }}/actions/runs/{}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
